language: python
python:
    - "2.7"
    - "3.5"
cache:
    - pip
before_install:
    - export TZ=America/Denver
install:
    - pip install --upgrade pip
    - pip install codecov
    - pip install .
    - pip install -r requirements.txt
    - pip install requests_mock
    - pip install pylint
script:
    - coverage run -m unittest discover && pylint --py3k --errors-only omniture
after_success:
    - coverage report -m
    - bash <(curl -s https://codecov.io/bash)
    - codecov
